from typing import Dict, List, Tuple

Merge = Tuple[Tuple[int, int], int]
VocabList = Dict[int, List[int]]

def build_info() -> str: ...
def encode_train(s: List[str]) -> List[Merge]: ...
def encode(s: List[str], merges: List[Merge]) -> List[int]: ...
def decode_string(ids: List[int], vocab_list: VocabList) -> str: ...
