from typing import List, Tuple

Merge = Tuple[Tuple[int, int], int]

def build_info() -> str: ...
def encode_train(s: List[str]) -> List[Merge]: ...
def encode(s: List[str], merges: List[Merge]) -> List[int]: ...
def decode_string(ids: List[int], merges: List[Merge]) -> str: ...
